// <auto-generated />
using System;
using FoxCoin;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FoxCoin.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FoxCoin.Models.Transaction", b =>
                {
                    b.Property<long>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount");

                    b.Property<long?>("ReceiverId");

                    b.Property<long?>("SenderId");

                    b.Property<DateTime>("Timestamp");

                    b.HasKey("TransactionId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new { TransactionId = 1L, Amount = 0m, ReceiverId = 2L, SenderId = 1L, Timestamp = new DateTime(2018, 12, 7, 18, 33, 50, 544, DateTimeKind.Utc) }
                    );
                });

            modelBuilder.Entity("FoxCoin.Models.UserAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Balance")
                        .IsConcurrencyToken();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("UserAccounts");

                    b.HasDiscriminator<string>("Discriminator").HasValue("UserAccount");

                    b.HasData(
                        new { Id = 1L, Balance = 100m, Username = "john" },
                        new { Id = 2L, Balance = 100m, Username = "jane" },
                        new { Id = 3L, Balance = 100m, Username = "sarah" },
                        new { Id = 4L, Balance = 100m, Username = "david" }
                    );
                });

            modelBuilder.Entity("FoxCoin.Models.CorporateAccount", b =>
                {
                    b.HasBaseType("FoxCoin.Models.UserAccount");

                    b.Property<string>("VatNumber");

                    b.ToTable("CorporateAccount");

                    b.HasDiscriminator().HasValue("CorporateAccount");
                });

            modelBuilder.Entity("FoxCoin.Models.PersonalAccount", b =>
                {
                    b.HasBaseType("FoxCoin.Models.UserAccount");

                    b.Property<long?>("FriendId");

                    b.HasIndex("FriendId");

                    b.ToTable("PersonalAccount");

                    b.HasDiscriminator().HasValue("PersonalAccount");
                });

            modelBuilder.Entity("FoxCoin.Models.Transaction", b =>
                {
                    b.HasOne("FoxCoin.Models.UserAccount", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId");

                    b.HasOne("FoxCoin.Models.UserAccount", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId");
                });

            modelBuilder.Entity("FoxCoin.Models.PersonalAccount", b =>
                {
                    b.HasOne("FoxCoin.Models.PersonalAccount", "Friend")
                        .WithMany("Friends")
                        .HasForeignKey("FriendId");
                });
#pragma warning restore 612, 618
        }
    }
}
