// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1;

namespace WebApplication1.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20181213052312_initialVersion")]
    partial class initialVersion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication1.Models.Planet", b =>
                {
                    b.Property<long>("PlanetId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<long>("Population");

                    b.HasKey("PlanetId");

                    b.ToTable("planets");
                });

            modelBuilder.Entity("WebApplication1.Models.Spaceship", b =>
                {
                    b.Property<long>("SpaceshipId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Max_capacity");

                    b.Property<long?>("PlanetId");

                    b.Property<int>("Utilization");

                    b.HasKey("SpaceshipId");

                    b.HasIndex("PlanetId");

                    b.ToTable("Spaceships");
                });

            modelBuilder.Entity("WebApplication1.Models.Spaceship", b =>
                {
                    b.HasOne("WebApplication1.Models.Planet", "Planet")
                        .WithMany()
                        .HasForeignKey("PlanetId");
                });
#pragma warning restore 612, 618
        }
    }
}
