movies = {}
movies[
    "Avengers:Endgame"] = "Avengers: Endgame is a 2019 American superhero film based on the Marvel Comics superhero team the Avengers, produced by Marvel Studios and distributed by Walt Disney Studios Motion Pictures. It is the sequel to 2012's The Avengers, 2015's Avengers: Age of Ultron, and 2018's Avengers: Infinity War, and the 22nd film in the Marvel Cinematic Universe (MCU). It was directed by Anthony and Joe Russo, written by Christopher Markus and Stephen McFeely and features an ensemble cast including Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth, Scarlett Johansson, Jeremy Renner, Don Cheadle, Paul Rudd, Brie Larson, Karen Gillan, Danai Gurira, Bradley Cooper, and Josh Brolin. In the film, the surviving members of the Avengers and their allies work together to reverse the damage caused by Thanos in Infinity War."
movies[
    "Captain Marvel"] = "Captain Marvel is a 2019 American superhero film based on the Marvel Comics character Carol Danvers. Produced by Marvel Studios and distributed by Walt Disney Studios Motion Pictures, it is the twenty-first film in the Marvel Cinematic Universe (MCU). The film is written and directed by Anna Boden and Ryan Fleck, with Geneva Robertson-Dworet also contributing to the screenplay. Brie Larson stars as Danvers, alongside Samuel L. Jackson, Ben Mendelsohn, Djimon Hounsou, Lee Pace, Lashana Lynch, Gemma Chan, Annette Bening, Clark Gregg, and Jude Law. Set in 1995, the story follows Danvers as she becomes Captain Marvel after Earth is caught in the center of a galactic conflict between two alien civilizations."
movies[
    "John Wick 3:Parabellum"] = "John Wick: Chapter 3 – Parabellum (also known as John Wick: Chapter 3 or simply John Wick 3) is a 2019 American neo-noir action film starring Keanu Reeves as the titular character. It is the third installment in the John Wick film series, following John Wick (2014) and John Wick: Chapter 2 (2017). The film is directed by Chad Stahelski[4] and written by Derek Kolstad, Shay Hatten, Chris Collins, and Marc Abrams, based on a story by Kolstad. It also stars Halle Berry, Laurence Fishburne, Mark Dacascos, Asia Kate Dillon, Lance Reddick, Anjelica Huston, and Ian McShane. In the film, ex-hitman John Wick finds himself on the run from legions of assassins after a $14 million contract is put on his head."
movies[
    "A Dog's Journey"] = "	A Dog's Journey is a 2019 American comedy-drama film directed by Gail Mancuso and written by W. Bruce Cameron, Cathryn Michon, Maya Forbes, and Wally Wolodarsky. The film is based on the 2012 novel of the same name by Cameron, and a sequel to the 2017 film A Dog's Purpose. The film stars Josh Gad, Dennis Quaid, Marg Helgenberger, Betty Gilpin, Kathryn Prescott, and Henry Lau."
movies[
    "The Hustle 2019"] = "The Hustle is a 2019 American comedy film directed by Chris Addison and written by Stanley Shapiro, Paul Henning, Dale Launer, and Jac Schaeffer. It is a female-centered remake of the 1988 film Dirty Rotten Scoundrels, which is itself a remake of the 1964 film Bedtime Story.[3] The film stars Anne Hathaway, Rebel Wilson, Alex Sharp, and Dean Norris, and follows two women who set out to con an internet millionaire."
